# Generated by Django 5.2.18 on 2026-10-08 06:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under investigation'), ('court', 'In court'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_cases', to=settings.AUTH_USER_MODEL, verbose_name='Lead investigator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('physical', 'Physical object'), ('digital', 'Digital media'), ('document', 'Document'), ('biological', 'Biological sample'), ('weapon', 'Weapon'), ('other', 'Other')], default='physical', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location_found', models.CharField(max_length=200, verbose_name='Where it was found')),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, upload_to='evidence/%Y/%m/', verbose_name='Attach file (photo, scan, disk image)')),
                ('file_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('status', models.CharField(choices=[('in_custody', 'In custody'), ('in_storage', 'In storage'), ('in_lab', 'At forensic lab'), ('in_court', 'In court'), ('released', 'Released'), ('disposed', 'Disposed')], default='in_custody', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=200, verbose_name='Stored at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='custody.case')),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_items', to=settings.AUTH_USER_MODEL)),
                ('current_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='held_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('collected', 'Collected'), ('transferred', 'Transferred'), ('stored', 'Placed in storage'), ('sent_to_lab', 'Sent to lab'), ('analyzed', 'Analyzed'), ('court', 'Presented in court'), ('released', 'Released'), ('disposed', 'Disposed')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('timestamp', models.DateTimeField(editable=False)),
                ('prev_hash', models.CharField(editable=False, max_length=64)),
                ('hash', models.CharField(editable=False, max_length=64)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handed_over_logs', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_logs', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_logs', to=settings.AUTH_USER_MODEL, verbose_name='New custodian')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='custody.evidence')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('investigator', 'Investigator'), ('analyst', 'Lab analyst'), ('viewer', 'Viewer (read only)')], default='viewer', max_length=20)),
                ('badge_number', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(blank=True, max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
